from tkinter import *
from tkinter import messagebox

root=Tk()
root.geometry=("660x333")
# widthxheight
root.minsize(730,750)
root.maxsize(730,750)
root.title("Dance Academy Form GUI")
def submit():
    print(firstnamevalue.get())
    print(surnamevalue.get())
    print(phonenovalue.get())
    messagebox.showinfo("Message","submitted")
# f1=Frame(root,bg="red")
# f1.grid()
top=Label(root,text="****Welcome to Shruti's Dance Academy****",font=('Comic Sans MS',12,'bold'))
top.grid(row=1,column=1)
end=Label(root,text="****Thankyou for visitng us****",font=('Comic Sans MS',12,'bold'))
end.grid(row=11,column=1,pady=30)
photo=PhotoImage("thank-you.png")
photo_label = Label(image=photo , height=100 , width=100)
photo_label.grid(sticky="e")

firstname=Label(root,text="   Firstname",font=('Comic Sans MS',10,'bold'),anchor='center',padx=12)
firstname.grid(row=2,column=0,pady=30)
surname=Label(root,text="Surname",font=('Comic Sans MS',10,'bold'),padx=12)
surname.grid(row=3,column=0,pady=30)
phoneno=Label(root,text="Phoneno",font=('Comic Sans MS',10,'bold'),padx=12)
phoneno.grid(row=4,column=0,pady=30)
c1=Checkbutton(root,text="  Kathak",font=('Comic Sans MS',10,'bold'),padx=50)
c1.grid(row=5,column=0,pady=30)
c2=Checkbutton(root,text="  Hip-Hop",font=('Comic Sans MS',10,'bold'),padx=50)
c2.grid(row=6,column=0,pady=30)
c3=Checkbutton(root,text="Contempory",font=('Comic Sans MS',10,'bold'),padx=50)
c3.grid(row=7,column=0,pady=30)
c4=Checkbutton(root,text="  Bharatanatyam",font=('Comic Sans MS',10,'bold'),padx=50)
c4.grid(row=8,column=0,pady=30)
btn=Button(text ="submit",command=submit,padx=6,font=('Comic Sans MS',10,'bold'),bg='steel blue')
btn.grid(row=9,column=1)
# variable classes in tkinter
# BooleanVar , DoubleVar , StringVar , IntVar
firstnamevalue= StringVar()
surnamevalue= StringVar()
phonenovalue= StringVar()
firstnameentry= Entry(root,textvariable= firstnamevalue,relief=SUNKEN,font=('Comic Sans MS',10,'bold'),bd=6,bg='steel blue',fg='white')
surnameentry= Entry(root,textvariable= surnamevalue,relief=SUNKEN,font=('Comic Sans MS',10,'bold'),bd=6,bg='steel blue',fg='white')
phonenoentry=Entry(root,textvariable=phonenovalue,relief=SUNKEN,font=('Comic Sans MS',10,'bold'),bd=6,bg='steel blue',fg='white')
firstnameentry.grid(row=2,column=1)
surnameentry.grid(row=3,column=1)
phonenoentry.grid(row=4,column=1)
root.mainloop()
